<?php
declare(strict_types=1);
require __DIR__ . '/config.php';
if (isset($_GET['logout'])) { session_unset(); session_destroy(); header('Location: index.php'); exit; }
$categories = db()->query('SELECT * FROM categories ORDER BY sort_order,title')->fetchAll();
$slug = trim($_GET['category'] ?? ''); $query = trim($_GET['q'] ?? ''); $params = []; $where = ['p.is_active=1'];
if ($slug !== '') { $where[] = 'c.slug=:slug'; $params['slug'] = $slug; }
if ($query !== '') { $where[] = 'p.title LIKE :q'; $params['q'] = '%' . $query . '%'; }
$sql = 'SELECT p.*,c.title category_title,c.slug FROM playlists p JOIN categories c ON c.id=p.category_id WHERE ' . implode(' AND ', $where) . ' ORDER BY p.id DESC'; $s = db()->prepare($sql); $s->execute($params); $playlists = $s->fetchAll(); $member = !empty($_SESSION['user_id']);
?><!doctype html><html lang="ru"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>BOMBALA — IPTV плейлисты</title><link rel="stylesheet" href="styles.css"></head><body><header class="topbar"><a class="logo" href="index.php"><img src="assets/bombala-logo.png" alt="BOMBALA"></a><nav><a href="#catalog">Плейлисты</a><a href="#how">Как подключить</a></nav><?php if ($member): ?><div class="account">Привет, <?= e($_SESSION['username']) ?> · <a href="?logout=1">Выйти</a></div><?php else: ?><a class="login" href="auth.php">⇥ Войти</a><?php endif; ?></header><main><section class="hero"><div><p class="eyebrow">● &nbsp; Каталог IPTV</p><h1>Смотри больше.<br><em>Управляй проще.</em></h1><p>Проверенные IPTV-плейлисты для телевидения, спорта, кино и детских каналов — в одном месте.</p><a class="primary" href="#catalog">Смотреть каталог →</a></div><div class="hero-card"><span>ПРЯМОЙ ЭФИР</span><strong>ТВОЙ ВЕЧЕР<br>В НОВОМ КАЧЕСТВЕ</strong><b>4K · FHD · HD</b></div></section><section class="catalog" id="catalog"><p class="eyebrow">● &nbsp; Библиотека</p><h2>Популярные <em>плейлисты</em></h2><form class="search"><input name="q" value="<?= e($query) ?>" placeholder="Поиск плейлистов..."><button>Поиск</button></form><div class="categories"><a class="<?= $slug === '' ? 'active' : '' ?>" href="index.php#catalog">Все</a><?php foreach ($categories as $c): ?><a class="<?= $slug === $c['slug'] ? 'active' : '' ?>" href="?category=<?= urlencode($c['slug']) ?>#catalog"><?= e($c['title']) ?></a><?php endforeach; ?></div><p class="found">Найдено <?= count($playlists) ?> плейлистов</p><div class="grid"><?php foreach ($playlists as $p): ?><article class="card"><div class="cover" style="--cover:<?= e($p['cover_color']) ?>"><span><?= e($p['quality']) ?></span><b><?= e($p['category_title']) ?></b></div><div class="card-body"><small><?= (int)$p['channels'] ?> каналов · обновлено сегодня</small><h3><?= e($p['title']) ?></h3><p><?= e($p['description'] ?? '') ?></p><?php if ($member): ?><a class="get-link" href="playlist.php?id=<?= (int)$p['id'] ?>">Открыть плейлист →</a><?php else: ?><a class="locked" href="auth.php">🔒 Войдите, чтобы получить доступ</a><?php endif; ?></div></article><?php endforeach; ?></div></section><section id="how" class="steps"><p class="eyebrow">● &nbsp; Быстрый старт</p><h2>Подключение за <em>3 минуты</em></h2><div><article><b>01</b><h3>Войдите в аккаунт</h3><p>Зарегистрируйтесь, чтобы открыть плейлисты.</p></article><article><b>02</b><h3>Выберите плейлист</h3><p>Найдите нужный набор каналов.</p></article><article><b>03</b><h3>Подключите в плеере</h3><p>Скопируйте M3U-ссылку в личном доступе.</p></article></div></section></main></body></html>
